language: java

notifications:
  email: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $TRAVIS_BUILD_DIR/libs

before_install:
  - cp src/main/resources/build.template.properties src/main/resources/build.properties
  - cp src/test/resources/test.template.properties src/test/resources/test.properties
  - cp src/main/webapp/WEB-INF/appengine-web.template.xml src/main/webapp/WEB-INF/appengine-web.xml

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install: true
script: ./travis_build.sh